DEFINE
  VAR __DS0FilterTable = 
    TREATAS({"Ja"}, 'Kalender'[I går])

  VAR __DS0FilterTable2 = 
    TREATAS({"B2019"}, 'Finansbudgetposter'[Budget Name])

  VAR __DS0FilterTable3 = 
    TREATAS({"I Går"}, 'Perioder'[Periode])

EVALUATE
  TOPN(
    502,
    SUMMARIZECOLUMNS(
      ROLLUPADDISSUBTOTAL('Kalender'[Dato], "IsGrandTotalRowTotal"),
      __DS0FilterTable,
      __DS0FilterTable2,
      __DS0FilterTable3,
      "Budget_MTD", 'Finansbudgetposter'[Budget MTD]
    ),
    [IsGrandTotalRowTotal],
    0,
    'Kalender'[Dato],
    1
  )

ORDER BY
  [IsGrandTotalRowTotal] DESC, 'Kalender'[Dato]
